// Group 7: Runtime (19 tools) — requires running game, all expectError since no game is running
module.exports = {
  name: 'Runtime',
  tests: [
    // These tools need a running game. Without one they should return fast errors, not timeout.
    {
      tool: 'get_game_scene_tree',
      description: 'Get game scene tree',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'get_game_node_properties',
      args: { path: 'root' },
      description: 'Get game node props',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'set_game_node_property',
      args: { path: 'root', property: 'visible', value: true },
      description: 'Set game node prop',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'execute_game_script',
      args: { code: 'return 42' },
      description: 'Execute game script',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'capture_frames',
      args: { count: 1 },
      description: 'Capture frames',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'monitor_properties',
      args: { path: 'root', properties: ['position'] },
      description: 'Monitor properties',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'start_recording',
      description: 'Start recording',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'stop_recording',
      description: 'Stop recording',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'replay_recording',
      args: { data: [] },
      description: 'Replay recording',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'find_nodes_by_script',
      args: { script_path: 'res://_verify_script.gd' },
      description: 'Find nodes by script',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'get_autoload',
      args: { name: 'mcp_runtime' },
      description: 'Get autoload',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'batch_get_properties',
      args: { paths: ['root'], properties: ['name'] },
      description: 'Batch get properties',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'find_ui_elements',
      args: { filter: {} },
      description: 'Find UI elements',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'click_button_by_text',
      args: { text: 'Start' },
      description: 'Click button by text',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'wait_for_node',
      args: { path: 'root', timeout: 1 },
      description: 'Wait for node',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'find_nearby_nodes',
      args: { position: [0, 0, 0], radius: 100 },
      description: 'Find nearby nodes',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'navigate_to',
      args: { path: 'root', target: [0, 0, 0] },
      description: 'Navigate to',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'move_to',
      args: { path: 'root', target: [0, 0, 0] },
      description: 'Move to',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
    {
      tool: 'watch_signals',
      args: { path: 'root', signals: ['tree_entered'] },
      description: 'Watch signals',
      expectError: true,
      timeout: 5000,
      validate: (_, text) => true,
    },
  ],
};
